# Generated by Django 3.0.7 on 2020-07-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyRegistrationAndLoginApplication', '0002_holidays_review'),
        ('departmentAndDesignationManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('employeeName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('emailAddress', models.EmailField(max_length=250, unique=True)),
                ('aadhaarNumber', models.CharField(max_length=20, unique=True)),
                ('panNumber', models.CharField(max_length=20, unique=True)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departmentAndDesignationManagement.Department')),
                ('designation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departmentAndDesignationManagement.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=250)),
                ('branchName', models.CharField(max_length=250)),
                ('branchAddress', models.CharField(max_length=250)),
                ('ifscCode', models.CharField(max_length=50)),
                ('accountNumber', models.CharField(default=None, max_length=100, unique=True)),
                ('accountType', models.CharField(max_length=200)),
                ('netBankingId', models.CharField(default=None, max_length=100, unique=True)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
                ('employeeId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employeesManagement.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=10)),
                ('streetName', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('postalCode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
                ('employeeId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employeesManagement.Employees')),
            ],
        ),
    ]
