# Generated by Django 3.0.7 on 2020-07-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('timeOfRegistration', models.TimeField(auto_created=True, auto_now=True)),
                ('dateOfRegistration', models.DateField(auto_created=True, auto_now=True)),
                ('companyId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('companyName', models.CharField(max_length=250)),
                ('companyAddress', models.CharField(max_length=250)),
                ('companyEmailAddress', models.EmailField(max_length=250, unique=True)),
                ('companyContactNumber', models.CharField(max_length=10)),
                ('companyGSTNumber', models.CharField(max_length=50, unique=True)),
                ('companyType', models.CharField(max_length=150)),
                ('companyWebsite', models.URLField()),
                ('companyDetails', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('adminId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('adminName', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
            ],
        ),
    ]
