# Generated by Django 3.0.7 on 2020-07-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyRegistrationAndLoginApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('holidayId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('holidayName', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True, auto_now=True)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=450)),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
            ],
        ),
    ]
