# Generated by Django 3.0.7 on 2020-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfRegistration', models.TimeField(auto_created=True, auto_now=True)),
                ('dateOfRegistration', models.DateField(auto_created=True, auto_now=True)),
                ('companyName', models.CharField(max_length=250)),
                ('companyAddress', models.CharField(max_length=250)),
                ('companyEmailAddress', models.EmailField(max_length=250, unique=True)),
                ('companyContactNumber', models.CharField(max_length=10)),
                ('companyGSTNumber', models.CharField(max_length=50, unique=True)),
                ('companyType', models.CharField(max_length=150)),
                ('companyWebsite', models.URLField()),
                ('companyDetails', models.CharField(max_length=500)),
            ],
        ),
    ]
