# Generated by Django 3.0.7 on 2020-07-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyRegistrationAndLoginApplication', '0002_holidays_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(max_length=250, unique=True)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('headOfDepartmentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('headOfDepartmentName', models.CharField(max_length=250, unique=True)),
                ('emailAddress', models.EmailField(max_length=250, unique=True)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
                ('departmentId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departmentAndDesignationManagement.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designationId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('designationName', models.CharField(max_length=250, unique=True)),
                ('companyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companyRegistrationAndLoginApplication.Companies')),
                ('departmentId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departmentAndDesignationManagement.Department')),
            ],
        ),
    ]
